---

- include_vars: /vagrant/workspace/ansible/aws_ecr.yml
  ignore_errors: yes

- include_vars: /vagrant/workspace/ansible/aws_networking.yml
  ignore_errors: yes

- include_vars: /vagrant/workspace/ansible/aws_rds.yml
  ignore_errors: yes

- include_vars: /vagrant/workspace/ansible/aws_ecs_cluster.yml
  ignore_errors: yes

- name: Generating main.tf for aws_ecs_service
  template:
    src: /vagrant/ansible/roles/ecs/./templates/terraform/aws_ecs_service/main.j2
    dest: /terraform/projects/aws_ecs_service/main.tf
  tags:
    - role_ecs_service
    - role_ecs_generate_tfs

- name: Generating output.tf for aws_ecs_service
  template:
    src: /vagrant/ansible/roles/ecs/./templates/terraform/aws_ecs_service/output.j2
    dest: /terraform/projects/aws_ecs_service/output.tf
  tags:
    - role_ecs_service
    - role_ecs_generate_tfs

- name: Generating variables.tf for aws_ecs_service
  template:
    src: /vagrant/ansible/roles/ecs/./templates/terraform/aws_ecs_service/variables.j2
    dest: /terraform/projects/aws_ecs_service/variables.tf
  tags:
    - role_ecs_service
    - role_ecs_generate_tfs

- name: Generating variables.tfvars for aws_ecs_service
  template:
    src: /vagrant/ansible/roles/ecs/./templates/terraform/aws_ecs_service/variables.tfvars.j2
    dest: /terraform/projects/aws_ecs_service/variables.tfvars
  tags:
    - role_ecs_service
    - role_ecs_generate_tfs

- name: Generating ECS Task Definition for aws_ecs_service
  template:
    src: /vagrant/ansible/roles/ecs/./templates/terraform/aws_ecs_service/task-definition.j2
    dest: /terraform/projects/aws_ecs_service/task-definition.json
  tags:
    - role_ecs_service
    - role_ecs_generate_tfs

- name: "Provision AWS ecs_service"
  terraform:
    force_init: yes
    project_path: /terraform/projects/aws_ecs_service
    variables_file: variables.tfvars
    state: present
  environment: "{{ aws_credentials }}"
  register: outs_aws_ecs_service
  tags:
     - role_ecs_terraform_ecs_service
     - role_ecs_apply_terraform

- name: Saving status in the Vagrant Workspace
  template:
    src: /vagrant/ansible/roles/ecs/./templates/varfiles/aws_ecs_service.j2
    dest: /vagrant/workspace/ansible/aws_ecs_service.yml
  tags:
    - role_ecs_terraform_ecs_service
    - role_ecs_apply_terraform

...
