---

- include_vars: /vagrant/workspace/ansible/aws_networking.yml
  ignore_errors: yes

- name: Generating main.tf for aws_bastion
  template:
    src: /vagrant/ansible/roles/ecs/./templates/terraform/aws_bastion/main.j2
    dest: /terraform/projects/aws_bastion/main.tf
  tags:
    - role_ecs_bastion
    - role_ecs_generate_tfs

- name: Generating output.tf for aws_bastion
  template:
    src: /vagrant/ansible/roles/ecs/./templates/terraform/aws_bastion/output.j2
    dest: /terraform/projects/aws_bastion/output.tf
  tags:
    - role_ecs_bastion
    - role_ecs_generate_tfs

- name: Generating variables.tf for aws_bastion
  template:
    src: /vagrant/ansible/roles/ecs/./templates/terraform/aws_bastion/variables.j2
    dest: /terraform/projects/aws_bastion/variables.tf
  tags:
    - role_ecs_bastion
    - role_ecs_generate_tfs

- name: Generating variables.tfvars for aws_bastion
  template:
    src: /vagrant/ansible/roles/ecs/./templates/terraform/aws_bastion/variables.tfvars.j2
    dest: /terraform/projects/aws_bastion/variables.tfvars
  tags:
    - role_ecs_bastion
    - role_ecs_generate_tfs

- name: "Provision AWS bastion"
  terraform:
    force_init: yes
    project_path: /terraform/projects/aws_bastion
    variables_file: variables.tfvars
    state: present
  environment: "{{ aws_credentials }}"
  register: outs_aws_bastion
  tags:
     - role_ecs_terraform_bastion
     - role_ecs_apply_terraform

- name: Saving status in the Vagrant Workspace
  template:
    src: /vagrant/ansible/roles/ecs/./templates/varfiles/aws_bastion.j2
    dest: /vagrant/workspace/ansible/aws_bastion.yml
  tags:
    - role_ecs_terraform_bastion
    - role_ecs_apply_terraform

...
