---

- include: roles/percona/tasks/decommission/packages/redhat.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  tags: role_percona

- include: roles/percona/tasks/decommission/packages/debian.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags: role_percona

...
