---

- include: roles/rev_proxy/tasks/decommission/packages/redhat.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- include: roles/rev_proxy/tasks/decommission/packages/debian.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

...
