---
- name: "Decommission AWS bastion"
  terraform:
    force_init: yes
    project_path: /terraform/projects/aws_bastion
    variables_file: variables.tfvars
    state: absent
  environment: "{{ aws_credentials }}"
  register: outs_aws_bastion
  tags:
     - role_ecs_terraform_bastion
     - role_ecs_apply_terraform

- stat: path=/vagrant/workspace/ansible/aws_bastion.yml
  register: aws_bastion_file_stat
  tags:
     - role_ecs_terraform_bastion
     - role_ecs_apply_terraform

- name: Deleting status in the Vagrant Workspace
  file:
    path: /vagrant/workspace/ansible/aws_bastion.yml
    state: absent
  when: aws_bastion_file_stat.stat.exists == True
  tags:
     - role_ecs_terraform_bastion
     - role_ecs_apply_terraform

...
