---

- include: "{{ percona_provision_packages }}"
  with_fileglob:
    - ./provision/packages*
  loop_control:
    loop_var: percona_provision_packages

- include: "{{ percona_provision_item }}"
  with_fileglob:
    - ./provision/*
  loop_control:
    loop_var: percona_provision_item

...
