---

 - name: Install libselinux as prerequisite for SELinux Ansible module
   yum:
     name: "[libselinux-python, libsemanage-python]"
     state: latest
   ignore_errors: true
   become: yes

 - name: Disable SELinux at next reboot
   selinux:
     state: disabled
   become: yes

 - name: Set SELinux in permissive mode until the machine is rebooted
   command: setenforce 0
   ignore_errors: true
   changed_when: false
   become: yes

...
