---

 - name: Setting vm.max_map_count=262144 for some apps like ElasticSearch
   sysctl:
    name: vm.max_map_count
    value: 262144
    sysctl_set: yes
    state: present
    reload: yes
   become: yes

...
