---

- name: Adding vagrant user into docker group
  user:
    name: vagrant
    groups: docker
    append: yes

- name: Copy ssh keys for Vagrant User.
  copy:
   src: "roles/docker/tasks/provision/sshkeys/{{ docker_users_item }}"
   dest: "/home/vagrant/.ssh/{{ docker_users_item }}"
   owner: vagrant
   group: vagrant
   mode: 0600
  with_items:
   - id_rsa.pub
   - id_rsa
  loop_control:
    loop_var: docker_users_item

...
