version: '3.3'

services:
  app_populate:
    image: theapp
    environment:
      - WAIT_FOR_DB=Yes
      - POPULATE_APP=Yes
      - MYSQL_USER=db_user
      - MYSQL_PASS=secret
      - MYSQL_DB=db_test
      - MYSQL_HOST=db_1
    networks:
      - theapp-network
    deploy:
      mode: global
      labels:
        - APP=THEAPP_POPULATOR
      resources:
        limits:
          cpus: '1'
          memory: 60M
        reservations:
          cpus: '0.1'
          memory: 15M
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 60s
  app_1:
    image: theapp
    environment:
      - WAIT_FOR_DB=Yes
      - POPULATE_APP=No
      - MYSQL_USER=db_user
      - MYSQL_PASS=secret
      - MYSQL_DB=db_test
      - MYSQL_HOST=db_1
    ports:
      - "5000:5000"
    networks:
      - theapp-network
    deploy:
      replicas: 2
      labels:
        - APP=THEAPP
      resources:
        limits:
          cpus: '1'
          memory: 60M
        reservations:
          cpus: '0.1'
          memory: 16M
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 60s

  db_1:
    image: percona:5.7
    volumes:
      - percona:/var/lib/mysql
    networks:
      - theapp-network
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=db_test
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=secret
    deploy:
      replicas: 1
      labels:
        - APP=PERCONA
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 256M
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 60s

volumes:
  percona:

networks:
  theapp-network:
    driver: overlay
