---

- include: roles/common/tasks/provision/packages/redhat.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- include: roles/common/tasks/provision/packages/debian.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

...
